version: '3'

services:
  fastapi-pyspark-server:
    build: .
    container_name: fastapi-pyspark
    restart: unless-stopped
    ports:
      - 6000:6000
    volumes:
      - .:/app

  nginx:
    image: nginx
    container_name: nginx-pyspark
    restart: unless-stopped
    ports:
       - "6111:6111"
    depends_on:
      - fastapi-pyspark-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf